version: 2.1

orbs:
  psscriptanalyzer: circleci/psscriptanalyzer@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0

parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  integration-test_install-check:
    executor: psscriptanalyzer/linux
    steps:
      - checkout
      - psscriptanalyzer/install
      - psscriptanalyzer/check:
          module: sample

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      - orb-tools/publish-dev:
          orb-name: circleci/psscriptanalyzer
          context: orb-publisher
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publisher
          requires:
            - orb-tools/publish-dev

  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test_install-check
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: circleci/psscriptanalyzer
          context: orb-publisher
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - integration-test_install-check
          filters:
            branches:
              only:
                - master
                - main
